name = "hayaseai"
account_id = "your-cloudflare-account-id"
workers_dev = true

[vars]
ENVIRONMENT = "production"

[build]
command = "npm install && npm run build"

main = "./openai.js"  # Pastikan file ini ada